### ISSUE TITLE
Achieving the impossible with swallow and Window Managers

### ISSUE THREAD

**Issue by equwal** [brownbishop/swallow#3]
If you are using a tiling window manager, you can modify your program launcher to use swallow before opening every program. Then, as soon as you launch a program, it will be managed instantly.

If you are using dwm for example and you open a program like firefox, you have to wait in the tag you want it to load in because X11 can't know you launched it until it appears. I asked about this in the suckless mailing list and at the StumpWM github and have been trying to do this for years.

Very nice program.

That is all!

Will update asap with script.

**Comment by brownbishop** [comment]
It can be done in Qtile with startup hooks

**Comment by equwal** [comment]
Indeed, turns out to be harder than I thought. There is XSetFocus, but actually getting the focus from the process will require figuring out how to get it from Xorg.

I converted it to C (because of course), will submit pull asap.
